---
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

include:
  - project: "univention/documentation/sphinx-docker"
    file: "pipeline/sphinx.yml"

docs-linkcheck:
  stage: "build"
  extends: ".sphinx-linkcheck-template"

docs-spelling:
  stage: "build"
  extends: ".sphinx-spelling-template"

docs-html:
  stage: "build"
  extends: ".sphinx-html-template"

docs-pdf:
  stage: "build"
  extends: ".sphinx-pdf-template"

docs-warnings:
  stage: "build"
  extends: ".sphinx-warnings-template"

docs-merge-to-one-artifact:
  stage: "merge"
  extends: ".sphinx-merge-template"
  needs:
    - job: "docs-html"
    - job: "docs-pdf"
    - job: "docs-spelling"
      artifacts: false
    - job: "docs-linkcheck"
      artifacts: false
  rules:
    - if: "$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH"
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: "manual"

docs-create-production-merge-request:
  stage: "production"
  extends: ".sphinx-docs-merge-request-template"
  needs:
    - job: "docs-merge-to-one-artifact"
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
...
