{{/*
SPDX-FileCopyrightText: 2023 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "common.names.fullname" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.ics }}
  INTERCOM_URL: {{ include "intercom-service.fqdn" $ | trim | quote }}
  BASE_URL: {{ include "intercom-service.fqdn" $ | trim | quote }}
  PORT: {{ $.Values.service.ports.http.containerPort | quote }}
  PROXY: {{ .proxy | quote }}
  LOG_LEVEL: {{ .logLevel | quote }}
  ORIGIN_REGEX: {{ .originRegex | quote }}
  # Keycloak
  {{- if .keycloak.enabled }}
  ISSUER_BASE_URL: {{ .issuerBaseUrl | quote }}
  KEYCLOAK_URL: "{{ if .keycloak.url }}{{ .keycloak.url }}{{ else }}{{ .default.protocol }}://{{ .keycloak.subdomain }}.{{ .default.domain }}{{ end }}"
  REALM_NAME: {{ .keycloak.realm | quote }}
  {{- end }}
  # Nordeck
  {{- if .nordeck.enabled }}
  NORDECK_MODE: {{ .nordeck.mode | quote }}
  NORDECK_URL: "{{ if .nordeck.url }}{{ .nordeck.url }}{{ else }}{{ .default.protocol }}://{{ .nordeck.subdomain }}.{{ .default.domain }}{{ end }}"
  {{- end }}
  # Matrix
  {{- if .matrix.enabled }}
  MATRIX_URL: "{{ if .matrix.url }}{{ .matrix.url }}{{ else }}{{ .default.protocol }}://{{ .matrix.subdomain }}.{{ .default.domain }}{{ end }}"
  MATRIX_SERVER_NAME: {{ .matrix.serverName | quote }}
  MATRIX_AS_SECRET: {{ .matrix.asSecret | quote }}
  {{- end }}
  # Nextcloud
  {{- if .nextcloud.enabled }}
  NC_ORIGIN: "{{ if .nextcloud.originUrl }}{{ .nextcloud.originUrl }}{{ else }}{{ .default.protocol }}://{{ .nextcloud.origin }}.{{ .default.domain }}{{ end }}"
  NC_URL: "{{ if .nextcloud.url }}{{ .nextcloud.url }}{{ else }}{{ .default.protocol }}://{{ .nextcloud.subdomain }}.{{ .default.domain }}{{ end }}"
  NC_AUDIENCE: {{ .nextcloud.audience | quote }}
  {{- end }}
  # OPENXCHANGE
  {{- if .openxchange.enabled }}
  OX_ORIGIN: "{{ if .openxchange.url }}{{ .openxchange.url }}{{ else }}{{ .default.protocol }}://{{ .openxchange.subdomain }}.{{ .default.domain }}{{ end }}"
  OX_AUDIENCE: {{ .openxchange.audience | quote }}
  {{- end }}
  # UCS
  {{- if .portal.enabled }}
  PORTAL_URL: "{{ if .portal.url }}{{ .portal.url }}{{ else }}{{ .default.protocol }}://{{ .portal.subdomain }}.{{ .default.domain }}{{ end }}"
  PORTAL_API_KEY: {{ .portal.apiKey | quote }}
  {{- end }}
  # Redis
  REDIS_HOST: {{ .redis.host | quote }}
  REDIS_PORT: {{ .redis.port | quote }}
  {{- if .redis.password }}
  REDIS_PASSWORD: {{ .redis.password | quote }}
  {{- end }}
  # OIDC
  CLIENT_ID: {{ .oidc.id }}
  CLIENT_SECRET: {{ .oidc.secret | quote }}
  {{- end }}
...
